# Generated by Django 4.2.4 on 2023-09-07 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0008_payment_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='Customer',
            new_name='Customers',
        ),
        migrations.RenameField(
            model_name='orderplaced',
            old_name='Product',
            new_name='Products',
        ),
    ]
